title = "TRIA.os MapLib Documentation" 
GitRepoUrl = "https://github.com/Tria-Studio/Tria-Escape-MapLib"

[docusaurus]
favicon = "tria os logo.png"

[home]
enabled = true
includeReadme = true

[[navbar.items]]
href = "https://discord.gg/tria"
label = "Discord Server"
position = "right"

[[navbar.items]]
href = "https://www.roblox.com/games/6311279644/"
label = "Game"
position = "right"