title = "TRIA.os MapLib Documentation" 
GitRepoUrl = "https://github.com/Tria-Studio/Tria-Escape-MapLib"

gitSourceBranch = "master"
changelog = true

[home]
enabled = true
includeReadme = true

[docusaurus]
favicon = "https://coderheck.github.io/assets/TRIAosLogoGradient.png"
scripts = [{src = "https://github.com/coderheck/maplib-open-source/blob/master/test.js", async = true}]

[[classOrder]]
section = "MapLib"
classes = ["MapLib"]

[[classOrder]]
section = "Features"
classes = ["Skills", "PlayerUI", "Settings", "Players", "Cleanup"]

[[classOrder]]
section = "Miscellaneous"
classes = ["Janitor"]

[[navbar.items]]
href = "https://discord.gg/tria"
label = "Discord Server"
position = "right"

[[navbar.items]]
href = "https://www.roblox.com/games/6311279644/"
label = "Game"
position = "right"

[[navbar.items]]
href = "/idk"
label = "coderheck"
position = "left"

[footer]
style = "dark"
copyright = "Copyright © 2019 - 2023 TRIA Corporation. Built with Moonwave and Docusaurus"