title = "TRIA.os MapLib Documentation" 
GitRepoUrl = "https://github.com/Tria-Studio/Tria-Escape-MapLib"

[home]
enabled = true
includeReadme = true

[[classOrder]] 
classes = ["MapLib", "Skills", "PlayerUI", "Settings"]

[[navbar.items]]
href = "https://discord.gg/tria"
label = "Discord Server"
position = "right"

[[navbar.items]]
href = "https://www.roblox.com/games/6311279644/"
label = "Game"
position = "right"