title = "TRIA.os MapLib Documentation" 
GitRepoUrl = "https://github.com/Tria-Studio/Tria-Escape-MapLib"
gitSourceBranch = "master"

[home]
enabled = true
includeReadme = true

[docusaurus]
favicon = "https://coderheck.github.io/assets/TRIAosLogoGradient.png"
scripts = [{src = "Main.js", async = false}]

[[classOrder]]
section = "MapLib"
classes = ["MapLib"]

[[classOrder]]
section = "Features"
classes = ["Skills", "PlayerUI", "Settings", "Players", "Cleanup", "Teleport"]

[[classOrder]]
section = "Miscellaneous"
classes = ["Janitor"]

[[navbar.items]]
href = "https://discord.gg/tria"
html = "<img src='https://drive.google.com/uc?export=view&id=1xMbDqto9ABFT3TvyyW1Dtuy2IwlrX1w3' style='max-width: 30px'/>"
position = "right"

[[navbar.items]]
href = "https://www.roblox.com/games/6311279644/"
html = "<img src='https://drive.google.com/uc?export=view&id=1olt2psI85yp4KJKj13g-3ED7Yv4Tknt9' style='max-width: 30px'/>"
position = "right"

[[navbar.items]]
href = "https://github.com/Tria-Studio/Tria-Escape-MapLib"
html = "<img src='https://drive.google.com/uc?export=view&id=1i9ezAZf4VKKyX-lE4tm6PwDLxk53Otql' style='max-width: 30px'/>"
position = "right"

[footer]
style = "dark"
copyright = "Copyright © 2019 - 2023 TRIA.os. Built with Moonwave and Docusaurus"